
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 1
 */
#pragma once

#include <react/renderer/core/ConcreteComponentDescriptor.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/components/view/ViewShadowNode.h>

namespace facebook {
namespace react {

extern const char NoCodegenSampleViewArkTSComponentName[] = "NoCodegenSampleViewArkTS";

class NoCodegenSampleViewArkTSProps : public ViewProps {
  public:
    NoCodegenSampleViewArkTSProps() = default;

    NoCodegenSampleViewArkTSProps(const PropsParserContext &context, const NoCodegenSampleViewArkTSProps &sourceProps, const RawProps &rawProps)
        : ViewProps(context, sourceProps, rawProps) {}
};

using NoCodegenSampleViewArkTSShadowNode = ConcreteViewShadowNode<
    NoCodegenSampleViewArkTSComponentName,
    NoCodegenSampleViewArkTSProps,
    ViewEventEmitter>;

class NoCodegenSampleViewArkTSComponentDescriptor final
    : public ConcreteComponentDescriptor<NoCodegenSampleViewArkTSShadowNode> {
  public:
    NoCodegenSampleViewArkTSComponentDescriptor(ComponentDescriptorParameters const &parameters)
        : ConcreteComponentDescriptor(parameters) {}
};

} // namespace react
} // namespace facebook
