/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 2
 */
#pragma once

#include "react/renderer/components/_react_native_oh_tpl_codegen_sample_package/ComponentDescriptors.h"
#include "RNOH/Package.h"
#include "NoCodegenSampleViewCAPIJSIBinder.h"

namespace rnoh {


class NoCodegenSampleCAPIPackage : public Package {
public:
    NoCodegenSampleCAPIPackage(Package::Context ctx) : Package(ctx){};

    std::vector<facebook::react::ComponentDescriptorProvider> createComponentDescriptorProviders() override {
        return {
            facebook::react::concreteComponentDescriptorProvider<
                facebook::react::NoCodegenSampleViewCAPIComponentDescriptor>(),
        };
    }

    ComponentJSIBinderByString createComponentJSIBinderByName() override {
        return {
            {"NoCodegenSampleViewCAPI", std::make_shared<NoCodegenSampleViewCAPIJSIBinder>()},
        };
    };

    EventEmitRequestHandlers createEventEmitRequestHandlers() override { return {}; }
};

} // namespace rnoh
