
/**
 * This code was generated by "react-native codegen-harmony"
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generatorVersion: 2
 */
#pragma once

#include "RNOH/CppComponentInstance.h"
#include "react/renderer/components/_react_native_oh_tpl_codegen_sample_package/ShadowNodes.h"

namespace rnoh {
class BaseCodegenSampleViewCAPIComponentInstance
    : public CppComponentInstance<facebook::react::NoCodegenSampleViewCAPIShadowNode> {
public:
    using CppComponentInstance::CppComponentInstance;

    void handleCommand(std::string const &commandName, folly::dynamic const &args) override {
        if (commandName == "emitNativeEvent") {
            this->onEmitNativeEventCommand(args[0].asString());
        }
        if (commandName == "emitCommandArgs") {
            this->onEmitCommandArgsCommand(args[0].asInt(), args[1].asDouble(), args[2].asDouble(), args[3].asString(),
                                           args[4].asBool());
        }
    }

    virtual void onEmitNativeEventCommand(std::string eventType) = 0;
    virtual void onEmitCommandArgsCommand(int intTest, float floatTest, double doubleTest, std::string stringTest,
                                          bool booleanTest) = 0;
};
} // namespace rnoh
