
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterH.js
 */
#pragma once

#include <react/renderer/components/view/ViewEventEmitter.h>


namespace facebook {
namespace react {
class NoCodegenSampleViewCAPIEventEmitter : public ViewEventEmitter {
 public:
  using ViewEventEmitter::ViewEventEmitter;

  enum class OnDirectEventStringEnumTest {
    Foo,
    Bar
  };

  static char const *toString(const OnDirectEventStringEnumTest value) {
    switch (value) {
      case OnDirectEventStringEnumTest::Foo: return "foo";
      case OnDirectEventStringEnumTest::Bar: return "bar";
    }
  }

  struct OnDirectEvent {
      int intTest;
    int intWithDefault;
    Float floatTest;
    Float floatWithDefaultTest;
    double doubleTest;
    double doubleWithDefaultTest;
    std::string stringTest;
    std::string stringWithDefaultTest;
    bool booleanTest;
    bool booleanWithDefaultTest;
    std::vector<std::string> arrayTest;
    OnDirectEventStringEnumTest stringEnumTest;
    std::vector<std::string> readOnlyArrayTest;
    std::string colorTest;
    };

  enum class OnBubblingEventStringEnumTest {
    Foo,
    Bar
  };

  static char const *toString(const OnBubblingEventStringEnumTest value) {
    switch (value) {
      case OnBubblingEventStringEnumTest::Foo: return "foo";
      case OnBubblingEventStringEnumTest::Bar: return "bar";
    }
  }

  struct OnBubblingEvent {
      int intTest;
    int intWithDefault;
    Float floatTest;
    Float floatWithDefaultTest;
    double doubleTest;
    double doubleWithDefaultTest;
    std::string stringTest;
    std::string stringWithDefaultTest;
    bool booleanTest;
    bool booleanWithDefaultTest;
    std::vector<std::string> arrayTest;
    OnBubblingEventStringEnumTest stringEnumTest;
    std::vector<std::string> readOnlyArrayTest;
    std::string colorTest;
    };

  struct OnReceivedCommandArgs {
      int intTest;
    Float floatTest;
    double doubleTest;
    std::string stringTest;
    bool booleanTest;
    };
  void onDirectEvent(OnDirectEvent value) const;

  void onBubblingEvent(OnBubblingEvent value) const;

  void onReceivedCommandArgs(OnReceivedCommandArgs value) const;
};
} // namespace react
} // namespace facebook
