
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/graphics/Color.h>
#include <vector>

namespace facebook {
namespace react {

enum class NoCodegenSampleViewCAPIStringEnumTest { Foo, Bar };

static inline void fromRawValue(const PropsParserContext &context, const RawValue &value,
                                NoCodegenSampleViewCAPIStringEnumTest &result) {
    auto string = (std::string)value;
    if (string == "foo") {
        result = NoCodegenSampleViewCAPIStringEnumTest::Foo;
        return;
    }
    if (string == "bar") {
        result = NoCodegenSampleViewCAPIStringEnumTest::Bar;
        return;
    }
    abort();
}

static inline std::string toString(const NoCodegenSampleViewCAPIStringEnumTest &value) {
    switch (value) {
    case NoCodegenSampleViewCAPIStringEnumTest::Foo:
        return "foo";
    case NoCodegenSampleViewCAPIStringEnumTest::Bar:
        return "bar";
    }
}

class NoCodegenSampleViewCAPIProps final : public ViewProps {
public:
    NoCodegenSampleViewCAPIProps() = default;
    NoCodegenSampleViewCAPIProps(const PropsParserContext &context, const NoCodegenSampleViewCAPIProps &sourceProps,
                                 const RawProps &rawProps);

#pragma mark - Props

    int intTest{0};
    int intWithDefault{42};
    Float floatTest{0.0};
    Float floatWithDefaultTest{42.5};
    double doubleTest{0.0};
    double doubleWithDefaultTest{42.5};
    std::string stringTest{};
    std::string stringWithDefaultTest{"foobar"};
    bool booleanTest{false};
    bool booleanWithDefaultTest{true};
    std::vector<std::string> arrayTest{};
    NoCodegenSampleViewCAPIStringEnumTest stringEnumTest{NoCodegenSampleViewCAPIStringEnumTest::Foo};
    std::vector<std::string> readOnlyArrayTest{};
    SharedColor colorTest{};
};

} // namespace react
} // namespace facebook
